version: '3.8'
services:
  db-user-service:
    image: postgres
    container_name: db-user-service
    ports:
      - "5450:5432"
    environment:
      - POSTGRES_DB= your db name
      - POSTGRES_USER=your db username
      - POSTGRES_PASSWORD=your db password
    volumes:
      - ./db-user-service:/var/lib/postgresql/data
    networks:
      - feign-client-network
volumes:
  db-user-service:
    driver: local
networks:
  feign-client-network:
